project_id = "hgnpriwaczmwnfgdjprr"

[functions.verify-purchase]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.play-rtdn-webhook]
verify_jwt = false

